### ISSUE TITLE
Need Attention on Role.js file and how it runs it `this.validate()` function

### ISSUE THREAD

**Issue by Prottoy2938** [TarikHuber/react-most-wanted#102]
In 

> packages/rmw-shell/src/pages/Roles

 folder, there's a file named **Role.js**. In that file, there's a function defined as `this.validate()`.  This function accepts an argument and validates the given argument.

`this.validate()` function is only called on `this.handleValueChange()` function. The problem here is that, when `this.validate()`function is called there's **no argument given to it**, Hence it will always return submit an error message no matter what.  

I suggest you should look up on that.

**Comment by TarikHuber** [comment]
Thx @Prottoy2938 . It was an old validation code. There is down the new one taht was used. I removed the code. thx again 😄
