### ISSUE TITLE
New Landing Page Design

### ISSUE THREAD

**Issue by Prottoy2938** [TarikHuber/react-most-wanted#103]
I am working on a new landing page design. I have created a new branch and started working there. 

What'd you say about this? Should I go?

**Comment by TarikHuber** [comment]
Hi @Prottoy2938 I'm fine with that. Would love to see it 😄

**Comment by Prottoy2938** [comment]
Well, there's one issue. I haven't found the landing page file. I found one folder which looked similar to the landing page and turns out it wasn't. That's why I closed the issue.

Can you point me to Landing page file?

**Comment by TarikHuber** [comment]
The LandingPage is in the folder src/pages/LandingPage . The only difference with other pages is that it's not in the routes in the config folder. It is added to the app as config property in the configs. The reason for that is that it improves performance if we total separate the LandingPage from rest of the app. There fore you won't have there the themes, locales and firebaseApp iside. That is also the reason that the dynamic thata is loaded using a REST API and not the Firebase SDK. While doing the new LP make sure not to use to much libraries and take care of the performance ;) and most importand use as less css as possible and no jQuery. To check all that deploy your landing page to a firebase project and make a ligthouse test. The current one is not the best looking but it deosn't look to bad but it is very fast.

**Comment by Prottoy2938** [comment]
What's the shortest way to change the **font color** of the navbar buttons?

Looks like it's taken from a package that you have created. Is there any `prop` that will help change the font color of that `ResponsiveMenu` component? Or I have to do it manually?

**Comment by TarikHuber** [comment]
Yes there is a prop. Just don't have it in my head. Checkout the component in the source code. All is open source. I use it in other porjects where the color is different.

**Comment by Prottoy2938** [comment]
Can you give me a list of all the useful features that are **built-in** or **pre-configured** on this starter application?

**Comment by TarikHuber** [comment]
Hmmm... most of them are in the README. I'm adding more and more and improving those that exist already.

**Comment by Prottoy2938** [comment]
I haven't used ` React ref ` on my recent React projects and I am not very sure about their use cases. In the **LandingPage.js** file you have created 4 properties that refer to React ref.

>   companies = React.createRef()
>   users = React.createRef()
>   about = React.createRef()
>   team = React.createRef()

But you didn't do anything with them except passing some of them down on a div. Should I keep them or remove them if I don't need them?

**Comment by TarikHuber** [comment]
They are used for the scrolling down. They are not used directly but dynamicaly with the menu buttons to scroll donw to those divs.

**Comment by TarikHuber** [comment]
@Prottoy2938 do you have a sneakpeak for me?

**Comment by Prottoy2938** [comment]
Well, it's not ready yet, besides I am working on another project. So it would take time
