### ISSUE TITLE
Possibility to bootstrap the project on an existing Firebase project in "Datastore Mode"

### ISSUE THREAD

**Issue by LouisonGitzinger** [TarikHuber/react-most-wanted#111]
Hello there, 
I successfully managed to setup RMW demo for my own, but I had to deactivate the *firestore* service because I tried to add RMW to an existing project that use Firestore in 'Datastore Mode'.
Do you have a workaround for that ?

Thank you in advance

**Comment by TarikHuber** [comment]
Hwat do you mean with datastore mode. Just make sure your firestore rules don't get overriden. RMW works on every firebase project. I have more then 30 runnjng on with RMW

**Comment by LouisonGitzinger** [comment]
I refer to this: https://cloud.google.com/datastore/docs/firestore-or-datastore
Once you initialise a Datastore DB in your project in *Datastore mode* you can not go back to the native *firestore* mode.
Hence, when I try to setup firestore using the firebase CLI (`firebase deploy --only firestore`), I get an error: 
```
Error: HTTP Error: 400, This operation is not available for Cloud Firestore projects in Datastore Mode.
```
which means that we can not actually deploy RMW using an axisting Firestore database if it is in *Datastore mode*

**Comment by LouisonGitzinger** [comment]
But don't bother with that, it is more for curiosity than a real need ☺️
