### ISSUE TITLE
when i generate a new app with different name i get an error about an A2HSComponent

### ISSUE THREAD

**Issue by ionutale** [TarikHuber/react-most-wanted#136]
am i the only one?

to reproduce the error run this:

```
npx create-react-app cool-app-name --template rmw
cd my-app
npm start
```

**Comment by UseMuse** [comment]
try before npm start, run npm install

**Comment by Proder** [comment]
I also get this error.


npx create-react-app my-app --template material-ui
cd my-app
npm i
npm start

**Comment by TarikHuber** [comment]
Sam as #138 and fixed
