### ISSUE TITLE
ReferenceError: A2HSProvider is not defined

### ISSUE THREAD

**Issue by papjul** [TarikHuber/react-most-wanted#138]
I followed instructions from README:
```
npx create-react-app my-app --template material-ui
cd my-app
npm start
```

I get an error:
```
ReferenceError: A2HSProvider is not defined
App
node_modules/base-shell/lib/containers/App/App.js:114

  111 |     lineNumber: 25,
  112 |     columnNumber: 15
  113 |   }
> 114 | }, /*#__PURE__*/_react.default.createElement(_Provider2.default, {
      | ^  115 |   __self: _this,
  116 |   __source: {
  117 |     fileName: _jsxFileName,
```

**Comment by papjul** [comment]
まてわん

Sent from Nine
________________________________
De : Tarik Huber <notifications@github.com>
Envoyé : lundi 18 mai 2020 17:03
À : TarikHuber/react-most-wanted
Cc: Julien Papasian; Author 
Objet : Re: [TarikHuber/react-most-wanted] ReferenceError: A2HSProvider is not defined (#138)

Closed #138 via 29c8172.

**Comment by TarikHuber** [comment]
@papjul  ?

**Comment by papjul** [comment]
Looks like my pocket wanted to speak Japanese, sorry ^^

Thank you for fixing the bug!
