### ISSUE TITLE
Login gets stuck on localhost.

### ISSUE THREAD

**Issue by zomars** [TarikHuber/react-most-wanted#14]
Hi Tarik!

For some reason since updating I can't login from localhost. The login window appears normally but once I login gets stuck in this screen:

<img width="489" alt="captura de pantalla 2017-11-07 a las 11 00 23" src="https://user-images.githubusercontent.com/3504472/32509581-f491e7a8-c3aa-11e7-90a6-75f913aa40c0.png">

The only clue I get from the console is this response: 

```
Received message: !_{"s":"/I0_1510077451720::authEvent","f":"I0_1510077451720","r":"I0_1510077451720","t":"42124609","c":3,"a":[{"type":"authEvent","authEvent":{"type":"unknown","eventId":null,"urlResponse":null,"sessionId":null,"error":{"code":"auth/no-auth-event","message":"An internal error has occurred."}}}],"g":false} from https://ding-pwa-staging-d4959.firebaseapp.com
log — client.js:181
```

If I deploy the app the login works fine on the test URL. This only happens on localhost. Any ideas of what could be happening?

Any help is deeply appreciated. Thanks for sharing this awesome project! :)

**Comment by petrakuk** [comment]
On test URL probably you deploy production mode, on localhost probably you try to run dev mode. Did you created another project in Firebase console ? example: [https://github.com/TarikHuber/react-most-wanted/blob/master/src/config.js](url)

**Comment by TarikHuber** [comment]
As @petrakuk mentioned `dev` and `prod` are using diferent firebase projects. You could also try to setup for both your prod project. If you still want to use the two different version you have to setup the authentication in your firebase project (activate email, gmail auth and setup all others you want to use).

Pleas @zomars  let us know if any of the mentioned suggestions could help.

**Comment by zomars** [comment]
I've setup both `dev` and `prod` to the same project. On my localhost I run `npm start` which is bound to `react-scripts start` so I'm assuming is running in dev mode.

**Comment by zomars** [comment]
Also, I don't know if this is related but currently the Auth service from firebase seems to be having a service disruption: https://status.firebase.google.com/

**Comment by TarikHuber** [comment]
@zomars I heard from other developers the same that the authentication service seams to have some problems. And also only with localhost. Did you made more changes to the initial RMW project? Did you try to login with a fresh fork or copy of RMW? If the problem persists with a fresh copy it would very probably be to the firebase authentication service.

**Comment by zomars** [comment]
I've only made changes to the config files, added a theme and made new components. Besides that I haven't altered the base project at all. I will try setting up a new project and see if that helps. Thanks!

**Comment by zomars** [comment]
I've made a new project and manually copied all my changes and configurations and the auth is working properly now.

**Comment by TarikHuber** [comment]
Hi @zomars do you have any new information's on this?

**Comment by zomars** [comment]
I couldn't pinpoint the issue I was having. I've cloned a new repo and everything is working fine now. I'm going to close this issue for now.
