### ISSUE TITLE
Is it possible to set default country for Firebase Mobile login

### ISSUE THREAD

**Issue by pravishanth** [TarikHuber/react-most-wanted#151]
Firebase mobile login shows 'US' as the default country, is it possible to change this to another country ?

[Firebase](https://firebase.google.com/docs/auth/web/firebaseui) suggests the below.
The default country to select in the phone number input can also be set. Refer to the list of supported country codes for the full list of codes. If unspecified, the phone number input will default to the United States (+1).

**Comment by TarikHuber** [comment]
Hi @pravishanth you send the configs in the Firebase Login UI so if it can be set accoriding to the docu you can do it. For the details pls check the docu. If you notice that we need to change how the Firebase UI is implementet so that you can do more changes let me know.

**Comment by pravishanth** [comment]
@TarikHuber, Firstly thank you and the entire team involved in making this repo, this is simply amazing!! You guys saved a week of my time!! 

Coming back to the issue, I see a blank page when I go to the [docs page](https://imgur.com/a/74tUtfL). I tried in all browsers without success, let me know if there is an alternative link for the docs.

**Comment by TarikHuber** [comment]
@pravishanth we are still workin on to create a documentation for React Most Wanted. What I ment with the docu is the Firebase documentation for the UI: https://github.com/firebase/firebaseui-web

**Comment by pravishanth** [comment]
Dear Tarik,

We have built our react app and we'd love the chat feature you guys have built in react-most-wanted.

I believe the chat feature is built on Firebase, Could you please advise how we could incorporate the chat feature into our react-app ? Are there any steps which you could advise ?


Warm Regards
Pravi

**Comment by TarikHuber** [comment]
Hi,

All components for the chat are anyway in the rmw-shell package. Just take
care to copy the required functions from the functions folder. All the
magic with the chat happens there ;)

If you get into specific problems let me know.

Cheers,
Tarik

**Comment by gaaytrimaa** [comment]
> Dear Tarik, We have built our react app and we'd love the chat feature you guys have built in react-most-wanted. I believe the chat feature is built on Firebase, Could you please advise how we could incorporate the chat feature into our react-app ? Are there any steps which you could advise ? Warm Regards Pravi

Hi Pravisanth, 
Can you please guide me how you solved the defaultCountry : "IN" in the config section for phone login. As according to the docs mentioned by @TarikHuber we know that we have to include this (defaultCountry property). But I am not able to figure that where to pass in this react most wanted config component.
More precisely in this react most wanted app the config is as follows: -
firebaseuiProps: {
      signInOptions: [
        //'google.com',
        //'facebook.com',
        //'twitter.com',
        //'github.com',
        //'password',
        'phone',
      ],
    },
Where will I pass (defaultCountry: "IN" ) in the above code. @TarikHuber @pravishanth 
Please guide

**Comment by TarikHuber** [comment]
@pravishanth @gaaytrimaa 
In the newest version the locale for the default locale can be set in the configs like this:

````
config:{
  locale:{
    defaultLocale:'de'
  }
````

The Firebase UI shoud load according to that the locale. The locales for the Firebase UI need to be build and located in the project. So if your is not in there let me know and I will add it. For now we have only en, de, es and ru.

**Comment by gaaytrimaa** [comment]
@TarikHuber Thank You for your response but the issue is not with locale I am attaching a screenshot below
![Screenshot (65)_LI](https://user-images.githubusercontent.com/38756022/97815040-6c7f4000-1cb1-11eb-8f8e-dd169ea8c3a0.jpg)
If you look in the image I want to the change the default US country code from +1 to India country code +91 when ever the screen of sign in loads so that the user don't have to do it manually from the dropdown.
In Firebase documentation for phone authentication, it is given that for setting default country code we need to use a property called as defaultCountry: "IN" or "US" or "GB" ,etc. I have implemented this successfully in plain javascript.
But in RMW I am not able to find where to write this.
Thanks & Regards for your amazing work.

**Comment by TarikHuber** [comment]
You can change this:

````
    firebaseuiProps: {
      signInOptions: [
        'google.com',
        'facebook.com',
        'twitter.com',
        'github.com',
        'password',
        'phone',
      ],
    },
````
in the configs to use this settings: https://github.com/firebase/firebaseui-web#configure-phone-provider

It would look like this:

````
    firebaseuiProps: {
      signInOptions: [
        'google.com',
        'facebook.com',
        'twitter.com',
        'github.com',
        'password',
         {
            provider: 'phone',
            defaultCountry: 'GB',
         }
      ],
    },
````

I like to use the provider ID-s hardcoded. Othervise we would need to import the whole firebase package just to get a simple string ;)

**Comment by gaaytrimaa** [comment]
@TarikHuber Excellent Sir it is working . Thank You so much. In India as a show of respect we touch teacher's feet to take blessings. I touch your feet for your amazing work which is imparting knowledge throughout the world. Please accept my respect.
Also, please let me know how can I contribute to making the documentation of this amazing project for you.
Thanks and Regards.

**Comment by TarikHuber** [comment]
@gaaytrimaa we are all here to help each other :) thank you for the kind words!
If you want to help with the project you can start where ever you want :)
thank you

**Comment by Sanjaynavgurukul** [comment]
@TarikHuber I want help set default country in my project
