### ISSUE TITLE
I suggest adding demo pages for errors 500, 403

### ISSUE THREAD

**Issue by UseMuse** [TarikHuber/react-most-wanted#157]
Hi
I suggest adding demo pages for errors 500, 403.

To switch to them, you need to throw an exception with status 500 or 403

I would be very grateful for such a work done

**Comment by UseMuse** [comment]
@TarikHuber since fetch is used everywhere, it looks like you will have to implement a fetch wrapper, something like useFetch, in which the response status code will be used to redirect to pages, 401,403,404?, 500. This is how I see it. You can do it differently, use axios everywhere, since it has interceptors, which greatly simplifies the work.

**Comment by TarikHuber** [comment]
@UseMuse would you like to make a nice 404 Page?

**Comment by jswelsh** [comment]
usually 404 pages tend to be more lighthearted in nature, do we want something like a western wanted poster  and dynamically load the error code for each? I can maybe try and put something together,
