### ISSUE TITLE
Example of material-ui-filter without redux

### ISSUE THREAD

**Issue by UseMuse** [TarikHuber/react-most-wanted#158]
I think it would be very useful to add an updated material-ui-filter (without redux) to the material-shell, with an example of its work.
I think I will come to this, but not soon, since there is no free time

**Comment by UseMuse** [comment]
I would be very grateful for such a work done

**Comment by TarikHuber** [comment]
YES. I'm working on the rmw to be completely without redux :) It just needs time.

**Comment by TarikHuber** [comment]
The filter without redux is done and in the `material-ui-shell`
