### ISSUE TITLE
Can't get install to work

### ISSUE THREAD

**Issue by 1jmj** [TarikHuber/react-most-wanted#161]
npx create-react-app test-app --scripts-version rmw-react-scripts

Results is a folder with just package.json and nothing else. 

NPX reports cra-template missing.

**Comment by Maxblake** [comment]
You have to choose which version you like to install:
Base shell: the basic react setup: routing, internationalization and async load.

npx create-react-app my-app --template base

Material UI shell: includes all features from the base shell expanded with Material-UI.

npx create-react-app my-app --template material-ui

React Most Wanted shell: Base shell + Material UI shell + Firebase

npx create-react-app my-app --template rmw

**Comment by lgargantini** [comment]
Hi there! Maybe updating this [README](https://github.com/TarikHuber/react-most-wanted/blob/d935d1f37aaf48b92ab3e21097958c2436410c97/packages/cra-template-rmw/template/src/pages/About/README.md) file and other similar references will avoid this.

**Comment by TarikHuber** [comment]
Thx for the suggestions. I will try to link all future readmes with the first and main one to avoid such situations.

**Comment by TarikHuber** [comment]
Could you try it with the new version and the command `npx create-react-app my-app --template rmw`

**Comment by TarikHuber** [comment]
Sometimes `yarn` is making porblems. You can force CRA to use `npm` with the command `npx create-react-app my-app --template rmw --use-npm`
