### ISSUE TITLE
material-ui-shell is for what

### ISSUE THREAD

**Issue by bonniePxx** [TarikHuber/react-most-wanted#166]
i just dont konw what the 'material-ui-shell' npm registry is for?

**Comment by TarikHuber** [comment]
You don't understand the use case for it or technicaly why there is a subproject "material-ui-shell"?

**Comment by bonniePxx** [comment]
> You don't understand the use case for it or technicaly why there is a subproject "material-ui-shell"?

i dont know why put the "material-ui-shell" and "base-shell" as a subproject, because it's some logic component。and i think we put them in the project under 'src' directories is much better.or is there some other reasons... wait your reply

**Comment by TarikHuber** [comment]
It's not just a logic component. Those are templates for different use cases. The "base-shell" is for projects where you don't want to use Firebase and Material-UI, "material-ui-shell" is for use cases where you want to use Material-UI but don't need Firebase. In the end "rmw-shell" is the template with all of them together. The reason I separeted them in subprojects is that anyone can use "base-shell" to create a Bootstrap template without doing the basic stuff like routing, intl and other from scratch. Anyone can use "material-ui-shell" to make a project with Material-UI but using it's own backend without Firebase.

I'm currently also working on the "rmw-shell-new" witch will replace the current "rmw-shell". I try to remove redux from it. A lot of developers critisize the usage of redux even Dan Abramow itself. 

I hope this clarifies for you why there are different subprojects. It's just to make this code reusable in any possible use case you can imagine. 

And YES "rmw-shells" are using from "material-ui-shell" just the prepared configs and override some of tham. That is the magic behind all of this. You should be able to change everything to your needs.

**Comment by bonniePxx** [comment]
thank you for replying. and i am just preparing a new project. i am just a little worry if there is some Specific needs in material-ui-shell,is there any way can i change it?

**Comment by TarikHuber** [comment]
What do you want to change?
