### ISSUE TITLE
Attempted import error: 'convertNumberSkeletonToNumberFormatOptions' is not exported from 'intl-messageformat-parser'.

### ISSUE THREAD

**Issue by cjayasur** [TarikHuber/react-most-wanted#170]
Failed to compile
./node_modules/intl-messageformat/lib/formatters.js
Attempted import error: 'convertNumberSkeletonToNumberFormatOptions' is not exported from 'intl-messageformat-parser'.
This error occurred during the build time and cannot be dismissed.

**Comment by TarikHuber** [comment]
Hi @cjayasur 
witch one of the projects did you try to build?

**Comment by hilias** [comment]
Hi, I found the same error using `npx create-react-app test --template material-ui`

**Comment by TarikHuber** [comment]
Hi, can you pls. try it again. Some intl packages where not in sync with the version. It should work now.

**Comment by hilias** [comment]
It seems that npm hasn't updated the package yet

**Comment by TarikHuber** [comment]
@hilias 🙄 I forget it to often 😞 
sorry, it should be updated now

**Comment by hilias** [comment]
Just tested and it's working ok. Thank You! 😄
