### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ravindar02** [TarikHuber/react-most-wanted#183]
Post installation "npx create-react-app my-app --template material-ui" when i use npm start i see below error

"./src/config/routes.js
Module not found: Can't resolve 'base-shell/lib/components/PrivateRoute/PrivateRoute' in '/Users/i/Desktop/react/onepointreact/src/config'"

Am i missing something?

**Comment by TarikHuber** [comment]
Can you pls try it again from scratch. Looks like the templade wasn't up to date. We had some breaking changes in the naming of the route components.

**Comment by ravindar02** [comment]
It worked. Thanks
