### ISSUE TITLE
Admin members checkbox not marked as checked

### ISSUE THREAD

**Issue by ekbox** [TarikHuber/react-most-wanted#202]
1. Navigate to chat
2. Create chat room
3. Create a group chat room
4. Select admins
5. Select an admin member by clicking on checkbox
6. Notice that checkbox is not marked as checked.

![Screenshot_20201128-135219_Chrome](https://user-images.githubusercontent.com/57198822/100526829-75184880-3181-11eb-8a72-cf89ed1af78c.jpg)

**Comment by TarikHuber** [comment]
Same issue and fixed https://github.com/TarikHuber/react-most-wanted/issues/201
