### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by jswelsh** [TarikHuber/react-most-wanted#206]
just a couple questions before I make the changes and push a pull request. 

`user_registrationg_graph_label: 'User registrations',` is the 'g' after registration intentional? 
Current -> will change to
`udateReceiverChatMessage` -> `updateReceiverChatMessage`
`updateReceiverUnred` -> `updateReceiverUnread`
`ArroWDropDownIcon `->`ArrowDropDownIcon`
`ArroWDropUpIcon` -> `ArrowDropUpIcon`

`searchvalue`  -> `searchValue` (camel case is the standard from what I've seen in the codebase)

let me know if these are intentional or if I should change.

**Comment by TarikHuber** [comment]
Thank you @jswelsh so much!
Spelling errors are not intentional. I'm sometimes very tired while working on this project :)

**Comment by jswelsh** [comment]
I'll get those done in the next day. I was just running through the code trying to reason with the flow of it. It's easy to catch these things when it's not your own work.
