### ISSUE TITLE
PERMISSION_DENIED: Permission denied

### ISSUE THREAD

**Issue by njirutitus** [TarikHuber/react-most-wanted#216]
I get this error when I try to send a message in public chat group after customization. Are there any firebase rules I need to change concerning this:

**Comment by TarikHuber** [comment]
Hi @njirutitus ,

yes you should at least have these rules: https://github.com/TarikHuber/react-most-wanted/blob/master/packages/rmw-shell/cra-template-rmw/template/firebase/database.rules.json

**Comment by njirutitus** [comment]
Thanks @TarikHuber for the help But it seems I had already published those rules yet am still getting the same error.

This is the warning that comes on the console.
`@firebase/database: FIREBASE WARNING: set at /group_chat_messages/public_chat/-MOkx4Q2EFcHwRJMJXFX failed: permission_denied `

**Comment by TarikHuber** [comment]
Could you pls check if you are using the project where you published the rules.

**Comment by njirutitus** [comment]
@TarikHuber I can confirm I am cause Everything works well apart from the public chat.

**Comment by njirutitus** [comment]
I finally figured it out.  My `/group_chat_messages/public_chat/` was missing the members child collection. Just added it manually from the firebase console with a child of `all: true`

**Comment by UseMuse** [comment]
iwhen I open  http://localhost:3000/posts no posts, when I click  fab btn
I have
PERMISSION_DENIED: Permission denied

**Comment by TarikHuber** [comment]
@UseMuse the posts are still work in progress. The have nothing to do with this issue.
