### ISSUE TITLE
documentation, visual architecture of the application

### ISSUE THREAD

**Issue by UseMuse** [TarikHuber/react-most-wanted#219]
diagrams showing key containers, purpose, dependencies

**Comment by TarikHuber** [comment]
pls stop writing wishes for the app as issues. You can make one for all but not every time one when a idea pops into your head

**Comment by UseMuse** [comment]
@TarikHuber I apologize

**Comment by TarikHuber** [comment]
@UseMuse no need for that. We just need to organise us a little bit more ;)
