### ISSUE TITLE
Needing to run npm install for functions folder

### ISSUE THREAD

**Issue by superkarn** [TarikHuber/react-most-wanted#22]
Hello.  When I tried to deploy to firebase, I got this error message:
```
Error: Error parsing triggers: Cannot find module 'glob'

Try running "npm install" in your functions directory before deploying.
```

Running `npm install` inside the functions directory resolved the issue.  It wasn't mentioned in the README file.  Is this required?  Or did I miss a step?

**Comment by TarikHuber** [comment]
Hi @superkarn . Thx for the PR you send and yes that is missing in the README. Whe have a wiki. There should be a more detailed instruction. Next week I will release a complete new version of RMW shat uses an app-shell over a npm module. I'm still working on that module to make it work like it should 😄 it's called rmw-shell you can chek it out on github.
