### ISSUE TITLE
solve my problem

### ISSUE THREAD

**Issue by vishvakumar8** [TarikHuber/react-most-wanted#223]
solve my problem

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path F:\ReactProject\robofriends-redux-master\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'F:\ReactProject\robofriends-redux-master\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2019-10-01T07_27_00_817Z-debug.log

_Originally posted by @arvind-coder in https://github.com/TarikHuber/react-most-wanted/issues/37#issuecomment-536908046_

**Comment by TarikHuber** [comment]
do you have more of the error log?

**Comment by vishvakumar8** [comment]
these errors only

**Comment by TarikHuber** [comment]
Could you explain more when it happens, what you have done before...

**Comment by Abdvkh** [comment]
Are you running `npx create-react-app your-app`?
