### ISSUE TITLE
[Question] What would be the preferred way to create relationships between different content types?

### ISSUE THREAD

**Issue by zomars** [TarikHuber/react-most-wanted#23]
For example, I want to be able to relate some Users to a specific Company and then they can CRUD Tasks but only of the Company they belong to. What would be the best approach? I would like to hear your opinions.

**Comment by TarikHuber** [comment]
Hi @zomars . This is not an easy one. Assigning a user to a company or vice versa is not the main problem. Making the data of that single company CRUD-able by just the users assigned to it is the main problem. To make it really work you would have to separate the data by the company UiD. That is for me the best solution when you are using the Firebase Realtime Database (maybe even the only one). Making the Create, Update and Delete would work also without the separation but the part with the Reading is problematic. You can make database rules that determine a collection of that that is visible and by reading it you get just the visible data. You can tough set the rules as that but then you would need to call every data (every child of a list) by it's UiD. That is probably not what you want. But also by separating the list in groups of user lists disables you to call all entries of the whole list at once. You would have to merge them on the client side if you have the rights to more than one of them. So dependency what specific user-case you have. We are using the grouping approach in one of our company projects. Most of the events for this are done with Firebase cloud functions. We even have a complete list and just sync the data for each company in a grouped list. Where the company users can see just they're data. They can't edit or delete it. That is in our case just for checking some information's. But a sync in both ways is also possible. Here it also depends on the use-case. If you have to much changes and events it would blow up your Firebase invoice ;)

**Comment by zomars** [comment]
Thanks for the insight! I'll see what I can do with this.

**Comment by TarikHuber** [comment]
@zomars  I'm closing this issue and created a [Gitter room](https://gitter.im/react-most-wanted/Lobby) for questions about RMW or rmw-shell.
