### ISSUE TITLE
clarification on /src/config/locales/ru.js

### ISSUE THREAD

**Issue by jswelsh** [TarikHuber/react-most-wanted#231]
I think this needs to be fixed but I have no idea, @UseMuse  can you confirm for me? 
`somerhing` I think wasn't translated properly because it is a spelling error in English.
`toast` also didn't get translated, not sure if that is ok. The others I assume are programming keywords so must remain.

dialog_message:`Диалоговое сообщение. Вы можете поместить сюда сколько угодно текста. 
  Задайте вопрос или покажите предупреждение перед удалением чего-либо. 
  Вы также можете задать для текста действия значение **somerhing**, например «Да, Удалить», и запустить это действие, передав опору «handleAction». 
  Он получает обратный вызов handleClose, с которым вы можете закрыть диалог, когда ваше действие будет выполнено.`,
  
toast_demo:'Демонстрация toast',

**Comment by UseMuse** [comment]
confirm
