### ISSUE TITLE
Freshly created Material UI project fails to compile

### ISSUE THREAD

**Issue by Aethix** [TarikHuber/react-most-wanted#233]
After attempting to create a new React project with the Material UI template, I am getting compilation errors.

I create and attempt to start the project with the following:

```
npx create-react-app my-app --template material-ui
cd my-app
yarn start
```

And after I do this, it gives me an error message saying that it failed to compile:

```
./node_modules/material-ui-shell/lib/containers/ImageUploadDialog/index.js
Module not found: Can't resolve 'react-easy-crop' in 'C:\redacted\my-app\node_modules\material-ui-shell\lib\containers\ImageUploadDialog'
```

If I attempt to install react-easy-crop and recompile, it gives me a new compilation error:

```
src\pages\MyAccount\MyAccount.js
  Line 130:20:  'PersonIcon' is not defined  react/jsx-no-undef
```

Is there an issue with the template, or is there some setup step I'm missing?

**Comment by UseMuse** [comment]
@Aethix update the version, it seems to have been fixed here https://github.com/TarikHuber/react-most-wanted/pull/222

**Comment by mmsaffari** [comment]
`PersonIcon` can be imported as `import PersonIcon from '@material-ui/icons/Person';` but this won't solve the first issue.

**Comment by TarikHuber** [comment]
The template should be up to date because the CI deployment uses that same script to deploy the application to production. I made it eactly that way to notice if I forget to deploy the template. The "build failed" notice is just because Browserstack sometimes works and sometims not.
