### ISSUE TITLE
It always fails to fetch this specific package, I have tried multiple times

### ISSUE THREAD

**Issue by mahadansar** [TarikHuber/react-most-wanted#235]
npx create-react-app my-app --template material-ui

I have tried running it multiple times from different isp's, in vs code/cmd/git bash.

error An unexpected error occurred: "https://registry.yarnpkg.com/@material-ui/icons/-/icons-4.11.2.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "E:\\W\\Invoice\\my-app2\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

![Untitled](https://user-images.githubusercontent.com/46062897/105181587-d0493480-5b4d-11eb-8370-a87dd0ec5055.png)
[yarn-error.log](https://github.com/TarikHuber/react-most-wanted/files/5842720/yarn-error.log)

**Comment by TarikHuber** [comment]
Hi, try the command from last comment in https://github.com/TarikHuber/react-most-wanted/issues/161

**Comment by mahadansar** [comment]
> Hi, try the command from last comment in #161

Thank you, it works.
