### ISSUE TITLE
SuperSelectField with multiple values

### ISSUE THREAD

**Issue by zomars** [TarikHuber/react-most-wanted#24]
I'm sorry to bother so much. I'm trying to use the `SuperSelectField` with the `multiple` attribute but I'm getting the `Uncaught TypeError: Cannot read property 'some' of null`  error.

I don't know is it is related to [this issue](https://github.com/Sharlaan/material-ui-superselectfield/issues/24), it seems pretty similar although the proposed solution includes the `multiple` attribute. When trying to use it here it's not working.

This is my current Field implementation:

```
<Field
  name="menucards"
  component={SuperSelectField}
  showAutocompleteThreshold={5}
  elementHeight={60}
  multiple={true}
  hintText={intl.formatMessage({id: 'menucards'})}>
  {menucardsSource.map((val, i) => {
    const menucards = {
      key: val.id || i
    }
    return (
      <div key={menucards.key} value={menucards} label={val.name}>{val.name}</div>
      )
    })}
</Field>
```

**Comment by TarikHuber** [comment]
Hi @zomars reporting issues is no bothering. Thx for that 😄 I think that @MaximilianPichler can help us here. He is working with Raphael on the superselectfield repo.

**Comment by TarikHuber** [comment]
Hi @zomars did you found a solution for the problem? There where a lot of fixes in SuperSelectfield

**Comment by zomars** [comment]
I've ended up using a `redux-form`'s `FieldArray` with multiple single `SuperSelectField` fields instead. So far this has worked good enough.

**Comment by TarikHuber** [comment]
Great then we can close this one 😄

**Comment by zomars** [comment]
A little demo:
![it-working1](https://user-images.githubusercontent.com/3504472/33181464-8a85e3e8-d02d-11e7-9aa6-912dfde1f7d8.gif)
