### ISSUE TITLE
On hover when Menu is in mini-mode?

### ISSUE THREAD

**Issue by jswelsh** [TarikHuber/react-most-wanted#240]
realized there isn't a way to know the menu items are beside the icons, should I throw the tooltip On hover & miniMode is true, for the menu items

![OnHover](https://user-images.githubusercontent.com/51499117/106083693-c6857b00-60d1-11eb-8788-8ad62dc0961c.gif)

**Comment by TarikHuber** [comment]
Hi @jswelsh , yes pls 😄
