### ISSUE TITLE
LTR mode shows text out of place

### ISSUE THREAD

**Issue by ekbox** [TarikHuber/react-most-wanted#241]
1. Chat placeholder on LTR is not position correctly, and adding text spills over.

2. Secondary text for rows is not position under primary
![Screenshot_20210127-205421_DuckDuckGo](https://user-images.githubusercontent.com/57198822/106092453-2f292380-60e3-11eb-92bb-570926e2fada.jpg)

**Comment by jswelsh** [comment]
@ekbox  sorry I'm just seeing this issue now. I believe I know the problem, I should have a fix shortly.

**Comment by jswelsh** [comment]
@ekbox I've made a pull request, 
It's a quick fix, but I suspect I need to find the true culprit. The direction seems to be overridden and I think it's [react-window](https://github.com/bvaughn/react-window). I need to look at this more.

@TarikHuber I will go through all the pages /components tomorrow and make sure there isn't any more `direction` overrides/resets.

**Comment by TarikHuber** [comment]
@jswelsh could you pls also adopt the new toggle APIs into the `rmw-shell` package? I published you changes to prod. 
Did you change something so the theme is differend?
![image](https://user-images.githubusercontent.com/11230962/106367126-aad3dc00-6340-11eb-9e81-0abfe3264e47.png)

The backhround was before white even in dark mode. Like this:

![image](https://user-images.githubusercontent.com/11230962/106367137-c343f680-6340-11eb-9a35-acfa25d17a16.png)

**Comment by jswelsh** [comment]
I will sort this out now, I suspect it has something to do with me switching the state `mode`: `'light' | 'dark' ` to `isDarkMode`:`Boolean` and converting it using a ternary into the values `light` or `dark` when interfacing with MUI theme. so I suspect it has to do with that change.

**Comment by jswelsh** [comment]
@TarikHuber do you know when it last showing as intended. I'm looking at the dev tools and the background is showing as `#424242` this is the default override of  [MUI dark mode theming](https://material-ui.com/customization/palette/#dark-mode) so maybe I fixed/broke this from a previous commit? and my previous assumption was incorrect. Maybe I need to look further back in commits to fix the culprit change. 

But this makes me feel like it would be better to override the default theming of the dark mode using the `createMuiTheme` and set the desired color as I don't already see overrides for the `palette.background.paper` and I'm pretty sure this is the correct behaviour just maybe not the desired set colors. I will say I personally have my environments set in dark mode and having a white background is not what I'd expect when turning on dark mode, but this is just a personal opinion.

thoughts?

**Comment by TarikHuber** [comment]
@jswelsh don't override the default themes. Maybe they changed them so the background is black now. Will check it this days.

**Comment by jswelsh** [comment]
@TarikHuber, I was trying to fix the rmw-shell with the new API's. when I'm testing it in development, I get an error of  `toggleThis is not defined` and in chrome dev tools I look at the source for the error, I get linked to `responsiveMenu` with an output of

```
"use strict";

exports.__esModule = true;
exports.default = void 0;

var _propTypes = _interopRequireDefault(require("prop-types"));

var _react = _interopRequireDefault(require("react"));

var _SwipeableDrawer = _interopRequireDefault(require("@material-ui/core/SwipeableDrawer"));

var _clsx = _interopRequireDefault(require("clsx"));

var _styles = require("@material-ui/core/styles");

var _Menu = require("material-ui-shell/lib/providers/Menu");

var _Theme = require("material-ui-shell/lib/providers/Theme");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _extends() { _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }

var drawerWidth = 240;
var iOS = process.browser && /iPad|iPhone|iPod/.test(navigator.userAgent);
var useStyles = (0, _styles.makeStyles)(function (theme) {
  return {
    toolbar: _extends({
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-end',
      padding: '0 8px'
    }, theme.mixins.toolbar),
    drawerPaper: {
      height: '100vh',
      width: drawerWidth,
      [theme.breakpoints.up('md')]: {
        position: 'relative'
      },
      transition: theme.transitions.create('width', {
        easing: theme.transitions.easing.sharp,
        duration: theme.transitions.duration.enteringScreen
      })
    },
    drawerPaperOpen: {
      height: '100vh',
      position: 'relative',
      whiteSpace: 'nowrap',
      width: drawerWidth,
      transition: theme.transitions.create('width', {
        easing: theme.transitions.easing.sharp,
        duration: theme.transitions.duration.enteringScreen
      })
    },
    drawerPaperClose: {
      height: '100vh',
      overflowX: 'hidden',
      transition: theme.transitions.create('width', {
        easing: theme.transitions.easing.sharp,
        duration: theme.transitions.duration.leavingScreen
      }),
      width: theme.spacing(1) * 7,
      [theme.breakpoints.up('sm')]: {
        width: theme.spacing(1) * 9
      }
    },
    hide: {
      display: 'none'
    }
  };
});

var ResponsiveMenu = function ResponsiveMenu(_ref) {
  var children = _ref.children,
      width = _ref.width;
  var classes = useStyles();

  var _useAppTheme = (0, _Theme.useTheme)(),
      isRTL = _useAppTheme.isRTL;

  var _useMenu = (0, _Menu.useMenu)(),
      isDesktop = _useMenu.isDesktop,
      isMiniMode = _useMenu.isMiniMode,
      isMenuOpen = _useMenu.isMenuOpen,
      isMobileMenuOpen = _useMenu.isMobileMenuOpen;

  var handleDrawerToggle = function handleDrawerToggle() {
    toggleThis('isMobileMenuOpen');
  };

  return /*#__PURE__*/_react.default.createElement("div", {
    style: {
      boxSizing: 'content-box'
    }
  }, /*#__PURE__*/_react.default.createElement(_SwipeableDrawer.default, {
    disableBackdropTransition: !iOS,
    disableDiscovery: iOS,
    variant: isDesktop ? 'permanent' : 'temporary',
    onClose: handleDrawerToggle,
    anchor: !isDesktop ? undefined : isRTL ? 'right' : 'left',
    classes: {
      paper: isDesktop ? (0, _clsx.default)(classes.drawerPaperOpen, !isMenuOpen && classes.drawerPaperClose, !isMiniMode && !isMenuOpen && classes.hide) : classes.drawerPaper
    },
    open: isDesktop ? isMenuOpen : isMobileMenuOpen,
    onOpen: handleDrawerToggle,
    ModalProps: {
      keepMounted: true // Better open performance on mobile.

    }
  }, children));
};

ResponsiveMenu.propTypes = process.env.NODE_ENV !== "production" ? {
  children: _propTypes.default.any
} : {};
var _default = ResponsiveMenu;
exports.default = _default;
module.exports = exports.default;
```

this all looks good, except in all of my `responsiveMenu` files I have 
```  
  const handleDrawerToggle = () => {
    console.log("TEST")
  }
```
 yet it shows 
```
  var handleDrawerToggle = function handleDrawerToggle() {
    toggleThis('isMobileMenuOpen');
  };
```
so clearly it's pulling old code, but none of my local files have ` toggleThis('isMobileMenuOpen');` at this time.  I get this when running the RMW-shell with 
`npm start` , 
logging into my account through gmail  
turning on dev tools
toggle device toolbar
clicking out of the mobile menu focus 
triggering `openDrawer()` -> `toggleThis()`

it should be noted that line is the same as what is currently on master. I've never experienced this kind of issue.

I've deleted all node files, all packagejson locks, reloaded visual basics, restarted my computer and dumped my browser data. reinstalled the RMW. still getting the same  problem.

**Comment by TarikHuber** [comment]
did you make a pull and after that npm install ?

**Comment by jswelsh** [comment]
I just resynced from master to make sure it wasn't that.  I was thinking that there may be some weird black magic of code being used from a deployed site, based on master. I'm stumped how this is even happening....I'm going to try on a different system.

**Comment by jswelsh** [comment]
when I install RMW-shell, does it download and compile code from GitHub to build on top of the other shells? if so then That's why my changes locally aren't affecting the responsive menu. I'm not used to building with a layered application, so I'm not sure how the installation works with the dependencies.

**Comment by TarikHuber** [comment]
The dark background is default on MUI now 
![image](https://user-images.githubusercontent.com/11230962/106397616-b1308980-640e-11eb-81f4-cc66c50df428.png)

**Comment by TarikHuber** [comment]
@jswelsh can you pls check the file https://github.com/TarikHuber/react-most-wanted/tree/master/packages/rmw-shell/src/components/MenuHeader

It's full of errorer when I try to build the project -.-

**Comment by jswelsh** [comment]
should be fine now.

I am trying to squash a few other bugs:
- clicking out of focus when using the mobile menu causes `toggleThis` not declared.
- native scrollbars in a few components are appearing in RTL for RMW shell 
- `SelectableMenuList` needs keys on items
should have these fixed today
