### ISSUE TITLE
Copy to clipboard feedback

### ISSUE THREAD

**Issue by jswelsh** [TarikHuber/react-most-wanted#249]
on landing page, the user can click the copy to clipboard but no feedback is given
![noFeedback](https://user-images.githubusercontent.com/51499117/106600513-621e4d80-650f-11eb-8e44-33ba2a0bb065.gif)

I propose an alert or , maybe a tooltip popup for 2 seconds. maybe something like this.
![new](https://user-images.githubusercontent.com/51499117/106600593-7cf0c200-650f-11eb-969d-8d607cc77fdb.gif)

**Comment by TarikHuber** [comment]
Sounds great 😄

**Comment by jswelsh** [comment]
anchor to button
![anchored](https://user-images.githubusercontent.com/51499117/106631453-a4588680-6531-11eb-8c71-f0cb88d4a853.gif)
or alert at bottom
![alertbottom](https://user-images.githubusercontent.com/51499117/106631546-b76b5680-6531-11eb-91c2-360ead2cc78f.gif)

**Comment by TarikHuber** [comment]
I leave that to you. What you like more 😄
