### ISSUE TITLE
Sign in with email does not work

### ISSUE THREAD

**Issue by halgrim** [TarikHuber/react-most-wanted#25]
If you authenticate with 'Sign in with email' or with 'Gmail", log out and then try to log in using 'Sign in with email' you will be redirected to the main page.
Expected: you should see pop up that you already have an account and prompt to log in using gmail.

Same behaviour on Demo page and on localhost.
If you clear browser data "Sign in with email" work again.

Tried to debug but I reached only to event from firekit ON_PERMISSION_CHANGED

**Comment by TarikHuber** [comment]
Thx @halgrim for repoting the issue. Will take a look on it ASAP.

**Comment by TarikHuber** [comment]
Hi @halgrim just to get it clear. It is not the same if you signup with email or gmail even the email is the same. For the authentication that are two different providers. You can tough link the email account to a gmail account. 

But no matter what causes the error, users should receive a proper error message.

**Comment by petrakuk** [comment]
Very strange, for me everything working properly and its never happens to me ?!

**Comment by TarikHuber** [comment]
OK. I get more reports about this issue. Will take a look on it ASAP. If someone has some additional information's pleas write them here so we can solve this problem. thx

**Comment by TarikHuber** [comment]
Fixed with the last commit.
