### ISSUE TITLE
Post does not publish and save for new records

### ISSUE THREAD

**Issue by ekbox** [TarikHuber/react-most-wanted#250]
1. Navigate to /posts
2. Create new post
3. Enter a text in text field
4. Click on publish
5. Verify new post is not shown on posts page
![Screenshot_20210202-182637_DuckDuckGo](https://user-images.githubusercontent.com/57198822/106689427-d21aeb00-6584-11eb-9d09-56f120833922.jpg)

**Comment by TarikHuber** [comment]
@ekbox thx for the report. But that is not a bug. I just didn't finish that part :(
Will try to do it ASAP

**Comment by TarikHuber** [comment]
I have removed the posts because the are not suitable for a basic template.
