### ISSUE TITLE
User Avatar not showing image

### ISSUE THREAD

**Issue by TarikHuber** [TarikHuber/react-most-wanted#253]
Hi @jswelsh 

ti looks like the User Avatar in the menu is not showing the image:
![image](https://user-images.githubusercontent.com/11230962/106732516-118f1900-6611-11eb-85bd-2f6b107a4475.png)

Could you pls check that. thx

**Comment by TarikHuber** [comment]
Could you also pls check this bug in the rmw-shell project:

![image](https://user-images.githubusercontent.com/11230962/106732900-89f5da00-6611-11eb-9d2a-e9c90eea76ce.png)

**Comment by jswelsh** [comment]
I've just recently fetched from master and deleted node modules and reinstalled them. so I should be on the most recent and mine is appearing, and If no photo is uploaded the Letter of the username is appearing. :confused:
![Screenshot from 2021-02-03 02-44-30](https://user-images.githubusercontent.com/51499117/106736009-c6054c80-65c9-11eb-8b0e-7e04f872425a.png)

**Comment by jswelsh** [comment]
@TarikHuber  I'm also not getting that error after running `npm run build`. the build script is running fine :confused:

**Comment by TarikHuber** [comment]
The avatar thing was probably a network problem on ma side but the bug in the build still remains. You won't see such bugs when you build the rmw-shell because Travis is not building that project. It's building the demo page. 

To see what bugs there are just create a new template using rmw-shell : `npx create-react-app my-app --template rmw` and check if there is everything ok

**Comment by jswelsh** [comment]
well, this was enlightening.  running `npx create-react-app my-app --template rmw` shows components operating as they should without native scrollbars showing in RTL mode. I've been trying to figure this out for the RMW shell for a while, in dev it doesn't seem to work correctly, yet here it is just fine.

**Comment by jswelsh** [comment]
also, I pushed changes to function naming to conform with react rules
