### ISSUE TITLE
useMenu

### ISSUE THREAD

**Issue by Albert80** [TarikHuber/react-most-wanted#255]
I saw the project and I tried to download rmw-shell, but after i run `yarn start` i got this error

> src/config/menuItems.js
>   Line 42:23:  React Hook "useMenu" is called in function "getMenuItems" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter  react-hooks/rules-of-hooks

**Comment by TarikHuber** [comment]
@jswelsh do you get the same error when starting the project?

**Comment by Albert80** [comment]
Yes! I did:
+ npx create-react-app my-app --template rmw
+ cd my-app
+ yarn start

And then i get the error, I tried with:
+ create-react-app my-app-2 --template rmw
+ cd my-app
+ yarn start

In material UI Shell `npx create-react-app my-app --template material-ui` didn't install one dependencie but i fixed without problems.

Did i miss something to do?

**Comment by jswelsh** [comment]
@Albert80 I'm looking into this now. I did make changes to `getMenuItems` but all instances should be `GetMenuItems`  not `getMenuItems`. I know I caught a few files missing from my initial PR, but I was certain I added them.

**Comment by Albert80** [comment]
I tried to find usages and I saw many getMenuItems instances.
Btw I didn't edit any file. So I'll try to change `getMenuItems` to `GetMenuItems`

**Comment by TarikHuber** [comment]
It should work now. Soryy @jswelsh didn't see that you where working on it. 

The problem was that you changed the `getMenuItems` to a componente to call the `useMenu` hook inside. Unfortunately that is realy only a function and not a component.

@Albert80 can you pls try again a fresh template.

**Comment by jswelsh** [comment]
@Albert80 @TarikHuber after a fresh `npx create-react-app my-app --template rmw` I changed the two instances of `GetMenuItems` to `GetMenuItems` in `test/my-app/src/config/menuItems.js` and it runs after `npm start`. I will find the last of the instances and make the PR. sorry about that

**Comment by TarikHuber** [comment]
I made that change already in the fix

**Comment by jswelsh** [comment]
@TarikHuber I'll look at those and see what you mean.

**Comment by jswelsh** [comment]
:facepalm: @TarikHuber  I see it now! thanks for the clarification.

**Comment by Albert80** [comment]
Great! It runs. Thank you guys! @TarikHuber @jswelsh
