### ISSUE TITLE
rmw-shell

### ISSUE THREAD

**Issue by devPadre** [TarikHuber/react-most-wanted#26]
Seems like everything gets over-run by the rmw-shell node module which has your firebase config in it. So any update to a project will overwrite this file and wreck the project?

**Comment by TarikHuber** [comment]
Hi @devPadre thx for the question. 

The rmw-shell is made to enable us to update the main project components when you already started using the rmw demo project as a starting point. If you use just a boilerplate any changes to that boilerplate will have no effect on your project. Even if those are bug fixes. We try with rmw-shell to update every project that uses RMW as boilerplate with new features and bug fixes without you needing to make changes to your code itself. 

I hope that [this Article](https://codeburst.io/beyond-create-react-app-cra-a2063196a124) can help.

First of all. You can change the code of this project on your local machine and change the client side functionality but you have no rights to publish database rules, firebase cloud functions and other project related features. That means that no one can wreck the react-most-wanted project on firebase.

You can change the firebase configs to use your project. While deploying to firebase don't forget to set your project ID to the firebase.src file. I need to write a more detailed documentation on how to use rmw-shell. 

This repo was at first a boilerplate project but now it evolved also into a production ready demo on how to use rmw-shell.

Let me know if you have any further questions.
