### ISSUE TITLE
Mono repo of submodules

### ISSUE THREAD

**Issue by PhearZero** [TarikHuber/react-most-wanted#260]
Here is an example of using submodules in a monorepo. 

- [PhearZero/react-most-wanted/packages](https://github.com/PhearZero/react-most-wanted/tree/master/packages)
- [Submodule Migration](https://github.com/PhearZero/react-most-wanted/blob/master/SUBMODULES.md)

pnpm is a good mono-runner but yarn works just as well.

**Comment by TarikHuber** [comment]
What benefits would be have with that?

**Comment by PhearZero** [comment]
Aims to solve two problems in general and still allow for mono-repo orchestration (yarn workspace | pnpm -r):
  - Allows for single issue buckets per project
  - Does not break the `npm install TarikHuber/package-name#hash` for installs.

**Comment by TarikHuber** [comment]
As far as I can see it it just separates the packages into different git projects. It was like that before. The reason I made it like this is that they are all tightly coupled so for me it makes more sense to have a single issue handler for all of them to avoid duplications. For example an issue that is in `base-shell` is only noticed in `rmw-shell`. That is the usual case. Maybe in future if there are more packages inside we can make the swith but for now I realy don't see any benefit of it for this usecase. 

Thank you for your suggestion and hellp :)
