### ISSUE TITLE
No redirect after logging in

### ISSUE THREAD

**Issue by bradenrupp** [TarikHuber/react-most-wanted#266]
When running locally or on firebase after a successful sign in, nothing happens. 
The app stays on: http://localhost:3000/signin?from=/dashboard

node version: v14.8.0
rmw-shell: 8.3.2

**Comment by TarikHuber** [comment]
Thx for the report. What login method did you use?
Do you have the same problem on the demo page? https://www.react-most-wanted.com/

**Comment by bradenrupp** [comment]
I tried using both the google sign in and email sign in. I can see the authentication entries being created in the firebase console.

The demo page works for me.

**Comment by TarikHuber** [comment]
Hi @bradenrupp I have tried it in dev mode and also by createing a fresh project and I could not replicate the issue. Could it be possible that you changed the FIrebase project and did not deploy the database rules? In that case the user sync after login would fail and it could then be that the app crashes.

**Comment by bradenrupp** [comment]
It looks like I inadvertently messed up the firebase.json so it was not deploying all the rules correctly. 
It's working for me now. 
Thanks!
