### ISSUE TITLE
Dependency mismatch between material-ui-shell and rmw prevents installation

### ISSUE THREAD

**Issue by slocod** [TarikHuber/react-most-wanted#285]
material-ui-shell peer dependencies need to be updated to use  @formatjs/intl-relativetimeformat@"8.x"
instead of the current: @formatjs/intl-relativetimeformat@"7.x"

Currently npx create-react-app my-app --template rmw 
fails with the current error:

npm ERR! Found: @formatjs/intl-relativetimeformat@8.1.8
npm ERR! node_modules/@formatjs/intl-relativetimeformat
npm ERR!   @formatjs/intl-relativetimeformat@"8.x" from the root project
npm ERR!   peer @formatjs/intl-relativetimeformat@"8.x" from rmw-shell@8.3.6
npm ERR!   node_modules/rmw-shell
npm ERR!     rmw-shell@"8.x" from the root project
npm ERR!   1 more (base-shell)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @formatjs/intl-relativetimeformat@"7.x" from material-ui-shell@1.3.4
npm ERR! node_modules/material-ui-shell
npm ERR!   material-ui-shell@"1.x" from the root project
npm ERR!   peer material-ui-shell@"1.x" from rmw-shell@8.3.6
npm ERR!   node_modules/rmw-shell
npm ERR!     rmw-shell@"8.x" from the root project

**Comment by ijtsmith** [comment]
I am still getting this error:

npm ERR! Found: @formatjs/intl-relativetimeformat@8.1.8
npm ERR! node_modules/@formatjs/intl-relativetimeformat
npm ERR!   @formatjs/intl-relativetimeformat@"8.x" from the root project
npm ERR!   peer @formatjs/intl-relativetimeformat@"8.x" from rmw-shell@8.3.6
npm ERR!   node_modules/rmw-shell
npm ERR!     rmw-shell@"8.x" from the root project
npm ERR!   1 more (base-shell)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @formatjs/intl-relativetimeformat@"7.x" from material-ui-shell@1.3.4
npm ERR! node_modules/material-ui-shell
npm ERR!   material-ui-shell@"1.x" from the root project
npm ERR!   peer material-ui-shell@"1.x" from rmw-shell@8.3.6
npm ERR!   node_modules/rmw-shell
npm ERR!     rmw-shell@"8.x" from the root project

**Comment by TarikHuber** [comment]
What version of npm and node do you have?
