### ISSUE TITLE
Cannot finish installation due to dependency between material-ui-shell and rmw, similar to #285

### ISSUE THREAD

**Issue by qhuy27** [TarikHuber/react-most-wanted#294]
Currently, cannot finish installation using 
npx create-react-app my-app --template material-ui or npx create-react-app my-app --template rmw
It still fails with the current error:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-app@0.1.0
npm ERR! Found: @formatjs/intl-relativetimeformat@8.1.8
npm ERR! node_modules/@formatjs/intl-relativetimeformat
npm ERR!   @formatjs/intl-relativetimeformat@"8.x" from the root project
npm ERR!   peer @formatjs/intl-relativetimeformat@"8.x" from rmw-shell@8.3.6
npm ERR!   node_modules/rmw-shell
npm ERR!     rmw-shell@"8.x" from the root project
npm ERR!   1 more (base-shell)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @formatjs/intl-relativetimeformat@"7.x" from material-ui-shell@1.3.4
npm ERR! node_modules/material-ui-shell
npm ERR!   material-ui-shell@"1.x" from the root project
npm ERR!   peer material-ui-shell@"1.x" from rmw-shell@8.3.6
npm ERR!   node_modules/rmw-shell
npm ERR!     rmw-shell@"8.x" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

I found this error to be the same as https://github.com/TarikHuber/react-most-wanted/issues/285

**Comment by TarikHuber** [comment]
what version of npm do you have and node?
I just tried the install command `npx create-react-app my-app --template rmw` and it worked out. It shows some warnings but with a such large dependncy list that is normal. After the instalation everything works as expected.

**Comment by qhuy27** [comment]
I'm using the latest Nodejs version:
node: v16.3.0
npm: 7.15.1
Ya, maybe this is the cause for the failed installation. I'll try to downgrade my node to the stable release ver.

**Comment by TarikHuber** [comment]
I would recommend to use the LTS version. Can you pls tell us how it worked out with the LTS version. thx

**Comment by qhuy27** [comment]
Yes, it's working fine with node LTS version. So the problem is likely to be with the newer version of node and npm.
Anyway, thank you very much for this awesome project and your quick response to issues. Keep up the good work 👍

**Comment by TarikHuber** [comment]
thx :)
