### ISSUE TITLE
Request notification permission does not work and cant send notifications

### ISSUE THREAD

**Issue by ekbox** [TarikHuber/react-most-wanted#295]
Navigate to https://www.react-most-wanted.com/firebase_messaging
Click on Request Notification button
Verifiy user does not see notification dialog to accept
Verify send button is disabled for new users

**Comment by TarikHuber** [comment]
Do you have multiple monitors? Sometimes when having more of them the dialog is not visible until you recise your browser. But that is some bug in windows and on all notification dialogs the same. Maybe you have already the permission. Did you try to remove the permission (if you have it) and try again. I just checked the link on chrome and it worked as expected.
