### ISSUE TITLE
No handler on dialog close/open

### ISSUE THREAD

**Issue by harm-meijer** [TarikHuber/react-most-wanted#296]
useQuestions gives me openDialog, closeDialog and setProcessing. How do I give the dialog an onClose handler?

**Comment by TarikHuber** [comment]
The `handleAction` gives you an `handleClose` as parameter:

```
handleAction: (handleClose) => {
              setProcessing(true)
              console.log('Doing some async stuff')

              setTimeout(() => {
                console.log('finished async stuff')
                //Do some stuff and then
                handleClose()
              }, 3000)
            },
```

**Comment by TarikHuber** [comment]
The demo code: https://github.com/TarikHuber/react-most-wanted/blob/master/packages/material-ui-shell/cra-template-material-ui/template/src/pages/DialogDemo/DialogDemo.js
