### ISSUE TITLE
Locale dropdown should show native description or code

### ISSUE THREAD

**Issue by srbala** [TarikHuber/react-most-wanted#30]
Locale dropdown should show native description or code needs to be selected. For example, if I selected German, after screen changed, it should language English in English not in German. Otherwise, once change language going back to other is problem.

**Comment by TarikHuber** [comment]
Hi @srbala. That can easely be changed in the locale. You can override them if you use rmw-shell like it is here in this project. If you want you can send a PR so the languages are as you like.
