### ISSUE TITLE
Handle routes for react-dom v6

### ISSUE THREAD

**Issue by catdevman** [TarikHuber/react-most-wanted#346]
I upgraded react-dom to v6 and got quite a few errors.  I fixed most of them pretty easy by updating places to work with `useLocation`, `useNavigate` and the like... Where things really broke down is working with Routes because of the way it takes and array of routes but also renders it's own default routes.  I am going to read a bit more to see if I could overwrite those but in general I think it would be a great upgrade because v6 I believe is 8kb instead of 23kb so pretty significant reduction in size and seems like a better API to use overall.

**Comment by catdevman** [comment]
I do believe this will require a "breaking" change.  Also I am up for some collaboration on this and have some time over the holidays, no work till Jan 4th!

**Comment by TarikHuber** [comment]
@catdevman first of all thank you for investing your time on the project. I would recommend to start with the base-shell and then go up to the other layers. If a breaking change is required we can do it. Maybe we can then update all packaged to the newest versions. Let me know what you think about.

**Comment by catdevman** [comment]
Yeah we're on the same page I was working on base shell last night 👍

**Comment by TarikHuber** [comment]
@catdevman I'm currently working on this migration. I will adopt the old react routes v3 way of handling routes by adding them to a simple list. This makes much more sense for this kind of template projects. When the `base-shell` is done you could help me migrate the other packages. This one will be released as major update so it doesn't break older apps.

**Comment by TarikHuber** [comment]
Forgto to mention this on the commit. The migration is done on base shell :)
