### ISSUE TITLE
Generating app with --template rmw intl-relativetimeformat dependency

### ISSUE THREAD

**Issue by jmgirven** [TarikHuber/react-most-wanted#348]
When trying to create a new app with `--template rmw` I am having an issue resolving dependencies:

```
$ npx create-react-app my-app --template rmw

Creating a new React app in C:\Users\jon\code\my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template-rmw...

added 1374 packages in 1m

163 packages are looking for funding
  run `npm fund` for details

Initialized a git repository.

Installing template dependencies using npm...
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-app@0.1.0
npm ERR! Found: @formatjs/intl-relativetimeformat@9.4.0
npm ERR! node_modules/@formatjs/intl-relativetimeformat
npm ERR!   @formatjs/intl-relativetimeformat@"9.x" from the root project
npm ERR!   peer @formatjs/intl-relativetimeformat@"9.x" from rmw-shell@11.0.6
npm ERR!   node_modules/rmw-shell
npm ERR!     rmw-shell@"11.x" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @formatjs/intl-relativetimeformat@"8.x" from base-shell@2.0.1
npm ERR! node_modules/base-shell
npm ERR!   base-shell@"2.x" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\jon\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jon\AppData\Local\npm-cache\_logs\2021-12-31T11_30_10_347Z-debug.log
`npm install --no-audit --save jss-rtl@0.x rmw-shell@11.x @formatjs/intl-relativetimeformat@9.x base-shell@2.x chart.js@3.x final-form@4.x final-form-arrays@3.x firebase@9.x firebaseui@6.x github-markdown-css@5.x intl@1.x material-ui-image@3.x material-ui-shell@3.x moment@2.x mui-rff@5.x notistack@2.x react@17.x react-beautiful-dnd@13.x react-chartjs-2@4.x react-countup@6.x react-custom-scrollbars@4.x react-dom@17.x react-easy-crop@4.x react-final-form@6.x react-final-form-arrays@3.x react-helmet@6.x react-intl@5.x react-ios-pwa-prompt@1.x react-linkify@^1.0.0-alpha react-markdown@7.x react-router-dom@6.x react-virtualized-auto-sizer@1.x react-window@1.x @mui/material@5.x @emotion/react@11.x @emotion/styled@11.x @fontsource/roboto@4.x @mui/icons-material@5.x @mui/styles@5.x @mui/lab@^5.0.0-alpha.49 @testing-library/jest-dom@^5.11.4 @testing-library/react@^12.1.0 @testing-library/user-event@^13.1.10` failed
```

It looks like in some places you are referencing `@formatjs/intl-relativetimeformat@9.x`, whereas in others you reference `@formatjs/intl-relativetimeformat@8.x`. E.g. here:

https://github.com/TarikHuber/react-most-wanted/blob/master/packages/base-shell/package.json#L25

```
$ node --version
v16.13.1
$ npm --version
8.1.2
```

Let me know if I can provide more information.

**Comment by TarikHuber** [comment]
Can you pls check it again?

**Comment by jmgirven** [comment]
That is definitely progress, thanks. However I am experiencing a follow on problem:

```
Installing template dependencies using npm...
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-rmw@0.1.0
npm ERR! Found: base-shell@2.0.3
npm ERR! node_modules/base-shell
npm ERR!   base-shell@"2.x" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer base-shell@"1.x" from rmw-shell@11.0.6
npm ERR! node_modules/rmw-shell
npm ERR!   rmw-shell@"11.x" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\jon\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jon\AppData\Local\npm-cache\_logs\2022-01-03T15_39_15_262Z-debug.log
`npm install --no-audit --save jss-rtl@0.x rmw-shell@11.x @formatjs/intl-relativetimeformat@9.x base-shell@2.x chart.js@3.x final-form@4.x final-form-arrays@3.x firebase@9.x firebaseui@6.x github-markdown-css@5.x intl@1.x material-ui-image@3.x material-ui-shell@3.x moment@2.x mui-rff@5.x notistack@2.x react@17.x react-beautiful-dnd@13.x react-chartjs-2@4.x react-countup@6.x react-custom-scrollbars@4.x react-dom@17.x react-easy-crop@4.x react-final-form@6.x react-final-form-arrays@3.x react-helmet@6.x react-intl@5.x react-ios-pwa-prompt@1.x react-linkify@^1.0.0-alpha react-markdown@7.x react-router-dom@6.x react-virtualized-auto-sizer@1.x react-window@1.x @mui/material@5.x @emotion/react@11.x @emotion/styled@11.x @fontsource/roboto@4.x @mui/icons-material@5.x @mui/styles@5.x @mui/lab@^5.0.0-alpha.49 @testing-library/jest-dom@^5.11.4 @testing-library/react@^12.1.0 @testing-library/user-event@^13.1.10` failed
```

So a conflict between packages trying to install `base-shell` `1.x` and `2.x`.

**Comment by tathagatl** [comment]
Hey @TarikHuber, still getting this error:
```
Installing template dependencies using npm...
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: generic-auditor@0.1.0
npm ERR! Found: chart.js@3.7.0
npm ERR! node_modules/chart.js
npm ERR!   chart.js@"3.x" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer chart.js@"2.x" from rmw-shell@11.0.9
npm ERR! node_modules/rmw-shell
npm ERR!   rmw-shell@"11.x" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 

```

**Comment by prasan2421** [comment]
### I have this issue now
stalling template dependencies using npm...
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: pawpaw@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.x" from the root project
npm ERR!   peer react@"17.x" from rmw-shell@11.0.10
npm ERR!   node_modules/rmw-shell
npm ERR!     rmw-shell@"11.x" from the root project
npm ERR!   15 more (@emotion/react, @emotion/styled, @mui/icons-material, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-custom-scrollbars@4.2.1
npm ERR! node_modules/react-custom-scrollbars
npm ERR!   react-custom-scrollbars@"4.x" from the root project
npm ERR!   peer react-custom-scrollbars@"4.x" from rmw-shell@11.0.10
npm ERR!   node_modules/rmw-shell
npm ERR!     rmw-shell@"11.x" from the root project
npm ERR!   1 more (material-ui-shell)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by TarikHuber** [comment]
What versions od node and npm do you have? And have you tried using with `--legacy-peer-deps``?

**Comment by prasan2421** [comment]
> $ node --version
> v16.13.1
> $ npm --version
> 8.1.2

'--legacy-peer-deps' doesnt seem to help. I have also tried installing the latest node and npm version.

**Comment by TarikHuber** [comment]
Did you try it again with the fixes I made today?

**Comment by prasan2421** [comment]
> Did you try it again with the fixes I made today?

Just did but got this error now.

Installing template dependencies using npm...
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: pawpaw_client@0.1.0
npm ERR! Found: react-router-dom@5.3.0
npm ERR! node_modules/react-router-dom
npm ERR!   react-router-dom@"5.x" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-router-dom@"6.x" from base-shell@2.3.3
npm ERR! node_modules/base-shell
npm ERR!   base-shell@"2.x" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by TarikHuber** [comment]
I have updated the template. Can you pls try it again. It should work now 100% 😄

**Comment by prasan2421** [comment]
> I have updated the template. Can you pls try it again. It should work now 100% 😄

It's working 1000% now 😄. Thank you.
