### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by sobiso** [TarikHuber/react-most-wanted#36]
OK that me... again ;)
Flow -> go to page -> signIn -> dashbard -> signOut
Why i no go back to LandingPage ? Even i put url without any string after "/" ?

**Comment by TarikHuber** [comment]
hi @sobiso 
It is absolutely no problem to write issues here :smile:
I'm happy that you are interested in the project and have such good questions.

The landing page is for the very first visit so only on the first visit it will/should be shown. 

Why did you close the issue?

**Comment by sobiso** [comment]
Because I found that on LandingPage is  
```  
if (!this.isAuthorised()) {
     history.push('/signin')
  }```

 so user was redirect to 'signin' page

**Comment by sobiso** [comment]
Can we add some button/text/link whatever to go to landing page( or some other page) after logout ?

**Comment by TarikHuber** [comment]
I'm open for PRs. Just keep in mind that the Landing Page has to be extremely fast ;) for the Lighthouse test. That is the only reason I created it :wink:
