### ISSUE TITLE
Error creating project: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by adnaan** [TarikHuber/react-most-wanted#37]
On executing, I get an error: 

```
$ npx create-react-app test-app --scripts-version rmw-react-scripts
...
Success! Created test-app at /Users/adnaan/code/js/test-app
Inside that directory, you can run several commands:

  yarn start
    Starts the development server.

  yarn build
    Bundles the app into static files for production.

  yarn test
    Starts the test runner.

  yarn eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd test-app
  yarn start

Happy hacking!
/Users/adnaan/code/js/test-app/node_modules/rmw-react-scripts/scripts/init.js:117
          throw err;
          ^

Error: ENOENT: no such file or directory, link '/Users/adnaan/code/js/test-app/functions/gitignore' -> '/Users/adnaan/code/js/test-app/functions/.gitignore'

```

Further : 

```
$ cd test-app
$ yarn start
yarn run v1.7.0
warning ../../../package.json: No license field
$ react-scripts start
env: node\r: No such file or directory
error Command failed with exit code 127.
```

ENV :

```
 node -v
v8.11.1
 npm -v
5.6.0
yarn -v
1.7.0
```

**Comment by TarikHuber** [comment]
This should fix the bug: https://github.com/TarikHuber/create-react-app/commit/0bd58176fcd1464c7fce51f6ee58c89f07654d9d

Thx for the issue report :smile:

**Comment by dholbrook86** [comment]
The issue doesn't seem to be fixed.
Clean install:
```
✨  Done in 7.84s.

Success! Created test-app at /Users/folder/test-app
Inside that directory, you can run several commands:

  yarn start
    Starts the development server.

  yarn build
    Bundles the app into static files for production.

  yarn test
    Starts the test runner.

  yarn eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd test-app
  yarn start

Happy hacking!
```

More:
```
yarn run v1.7.0
$ react-scripts start
env: node\r: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
ENV:
```
node -v
v8.11.3
npm -v
5.6.0
yarn -v
1.7.0

**Comment by TarikHuber** [comment]
Hi @dholbrook86 did you try it out with just npm?

**Comment by dholbrook86** [comment]
I think that's what I did the first time I tried it. Then I wiped it clean and tried yarn.
I can give it another shot.

**Comment by dholbrook86** [comment]
Thank you so much for your help @TarikHuber!

**Comment by dholbrook86** [comment]
I was able to get it to work with the following steps.

`npx create-react-app test-app --scripts-version rmw-react-scripts`

`cd test-app`

`npm install -g node-pre-gyp`

`npm i`

`npm start`

The `node-pre-gyp` was tripping me up. I didn't have this globally installed.

**Comment by arvind-coder** [comment]
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path F:\ReactProject\robofriends-redux-master\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'F:\ReactProject\robofriends-redux-master\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2019-10-01T07_27_00_817Z-debug.log

**Comment by venkateshece1105** [comment]
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/s', '/c', 'start', '""', '/b', '"http://localhost:3000/"' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the project@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\system8\AppData\Roaming\npm-cache\_logs\2019-12-11T11_51_45_014Z-debug.log

**Comment by TarikHuber** [comment]
Can you try to install the original Creat React App without any custom template.

**Comment by Vipulgorana** [comment]
my app ran yesterday perfectly and then today  I resume coding and boom I saw this same error !!

**Comment by bragamat** [comment]
I had a similar problema, solved with: 

`yarn global remove create-react-app`

and then `npx create-react-app my-app`

**Comment by Abdvkh** [comment]
Also can use:
`npm uninstall -g create-react-app`

**Comment by muflikhahisna0** [comment]
1. dfds
2. dsfsd

- 

> `fsd            

> 

> 

> 

> ### **_mn`_**

- sdfsd
- [fds[](url)]([url](url))

**Comment by yaminzan** [comment]
only can run this commend line it will working 
npm install -g node-pre-gyp
