### ISSUE TITLE
Can't login to app

### ISSUE THREAD

**Issue by Molnfront** [TarikHuber/react-most-wanted#377]
I have just installed and configured everything. Just running it with the same firebase config for dev, prod and devp. Have'nt yet figured out that part.

But I am not able to sign in. It only shows the sign in page and there are lots of errors. 

FCM and everything is configured.
<img width="1201" alt="Skärmavbild 2022-03-23 kl  13 32 43" src="https://user-images.githubusercontent.com/935328/159700598-edffc67a-3d51-47c6-a3ad-062127667a47.png">

PS! It worked with your firebase config...

**Comment by TarikHuber** [comment]
Did you add localhost to accepted domains? 
![image](https://user-images.githubusercontent.com/11230962/159738630-93cde3c3-17c5-437d-9d3d-043475d88134.png)

**Comment by Molnfront** [comment]
Yup, allready had everything setup.

**Comment by Molnfront** [comment]
Do I need a Firebase db? I already have a Firestore db. It complains now about my databaseURL.

**Comment by Molnfront** [comment]
My latest chrome logs:
[localhost-1648057330428.log](https://github.com/TarikHuber/react-most-wanted/files/8335319/localhost-1648057330428.log)
[localhost-1648057361604.log](https://github.com/TarikHuber/react-most-wanted/files/8335322/localhost-1648057361604.log)
[localhost-1648057369178.log](https://github.com/TarikHuber/react-most-wanted/files/8335323/localhost-1648057369178.log)

**Comment by Molnfront** [comment]
FCM is configured and I have added the public key.

**Comment by Molnfront** [comment]
It did work! If try to sign in with an account that is not registered itseems to fail silently. I just get back to the sign in..

**Comment by Molnfront** [comment]
Nope, it did not work

**Comment by Molnfront** [comment]
Now it's working. Had to setup a firebase db.

**Comment by TarikHuber** [comment]
@harshkurra why should you not be able to use firestore? You can use both db at the same time.

**Comment by harshkurra** [comment]
@TarikHuber Yes, after making a few changes, I am able to use the firestore as expected.
