### ISSUE TITLE
Problems installing the app

### ISSUE THREAD

**Issue by kujaomega** [TarikHuber/react-most-wanted#38]
After using the  `npx create-react-app test-app --scripts-version rmw-react-scripts` command, I get the following error:

/home/XXX/Projects/react-most-wanted/test-app/node_modules/rmw-react-scripts/scripts/init.js:117
          throw err;
          ^

Error: ENOENT: no such file or directory, link '/home/XXX/Projects/react-most-wanted/test-app/functions/gitignore' -> '/home/XXX/Projects/react-most-wanted/test-app/functions/.gitignore'

Then, when I make the `yarn start`m, I get the following error:

`/usr/bin/env: ‘node\r’: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

My OS is Ubuntu 16.04

**Comment by TarikHuber** [comment]
Hi @kujaomega ,

Have you checked if it is related to #37

**Comment by kujaomega** [comment]
Hi @TarikHuber,

Yes, thanks, that solved the issue. Your repository seems interesting.

Kind regards
