### ISSUE TITLE
Can't create new components that take advantage of react-intl

### ISSUE THREAD

**Issue by Fearful** [TarikHuber/react-most-wanted#39]
Hi!
First off, impressive work, especially for my current usecase,
I already write a react app with react-intl but my webpack build didn't work well enough and this projects fits perfectly.

I wanted to attach a Header and Footer component and I'm getting the following error:
` <IntlProvider> needs to exist in the component ancestry`

Normally i would see the provider but I coudn't find it anywhere on the src
I'm adding the Header component to the index inside the router, as it should accept components out side the switch, everything seems fine until I try to use the intl `injectIntl(Header)` and add the references required

Is there a configuration I'm missing?

Thanks in advantage

**Comment by TarikHuber** [comment]
Hi @Fearful ,

Thx 😄 

The IntlProvider is set in the `rwm-shell` Root component. That one is in the App component we use in our project so everything outside of that will have no IntlProvider. Here are two possible solutions for you:

1 - Try to use your Header and Footer inside the App component of `rmw-shell` and with the routes switch. Maybe you can explain more what your goal is. 
2 - Add a IntlProvider on your own outside the App component. Downside of this one is that you have to manage the language settings and messages on your own. But from the `react-intl` prespective it is no problem to have more Providers inside each other. 

Let me know if this could help.

**Comment by Enough7** [comment]
Hey @TarikHuber,
unfortunately if I change the landingPage to `lazy(() => import('../pages/Home/Home')),` in `config.js` it returns the Error `Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.`. I know the cause of this error but don't understand how to fix it. The shell's code is quite hard to read for somebody who is not familiar with node

**Comment by TarikHuber** [comment]
Hi. Don't make the landing page async. It is the first page to load and an asyn does not make sense. After the first load it is already offline first and after that it doesn't matter anyway. If the landing page is to big you can splitt it but the first part should be sync. The demo page of rmw js madr like that. We even load the rest only on a scroll event ;)

**Comment by Enough7** [comment]
@TarikHuber I did not make it async, it was already async as I downloaded RMW. 
`config.js`
```Javascript
  pages: {
    LandingPage: import('../pages/Home/Home'),
    PageNotFound: lazy(() => import('../pages/PageNotFound/PageNotFound')),
  }
```
does not work as well :(

**Comment by TarikHuber** [comment]
That is not async. Only the one with lazy is async.

**Comment by Enough7** [comment]
@TarikHuber Ok, but how do I change the landingpage to eg. Home?

**Comment by TarikHuber** [comment]
Can you explain more your use case?

**Comment by Enough7** [comment]
@TarikHuber I added a `<Redirect.../>` to `/home` in the landing page and set every route in `routes.js` to an `unauthorizedRoute`
