### ISSUE TITLE
Error creating new application

### ISSUE THREAD

**Issue by xram** [TarikHuber/react-most-wanted#40]
I'm running the command: `npx create-react-app test-app --scripts-version rmw-react-scripts`

And it is resulting in an error like the following:

```
/Users/xram/Development/test-app/node_modules/rmw-react-scripts/scripts/init.js:117
          throw err;
          ^

Error: ENOENT: no such file or directory, link '/Users/xram/Development/test-app/functions/gitignore' -> '/Users/xram/Development/test-app/functions/.gitignore'
```

And indeed, `/Users/xram/Development/test-app/functions/gitignore`, doesn't exist.

**Comment by TarikHuber** [comment]
Hi @xram ,

Thx for the bug report. The next version fixes the problem.
