### ISSUE TITLE
cannot run fresh created project

### ISSUE THREAD

**Issue by sebastianovide** [TarikHuber/react-most-wanted#42]
I've just started a project with these commands: 

```(08:56:59):~/dev/tmp$ history 
14911  [2018-11-16 08:49:36] npx create-react-app test-app --scripts-version rmw-react-scripts
14912  [2018-11-16 08:52:57] cd test-app
14913  [2018-11-16 08:53:04] npm start
```
and I get: 

```Failed to compile.

./node_modules/rmw-shell/es/containers/Root/Root.js
Module not found: Can't resolve '@date-io/moment' in '/Users/sovide/dev/tmp/test-app/node_modules/rmw-shell/es/containers/Root'
^C```

**Comment by TarikHuber** [comment]
Hi @sebastianovide ,

Sorry for this. I have to update the template. rmw-shell has a new peer dependency. Just install the date-io with:

```npm i -S @date-io/moment```

and it should work again.

**Comment by TarikHuber** [comment]
Hi @sebastianovide I just updated the scripts so they install the missing dependenices. If you wan't you can try it with a fresh project.
