### ISSUE TITLE
just installed it and it "Failed to compile" 

### ISSUE THREAD

**Issue by terchris** [TarikHuber/react-most-wanted#43]
Failed to compile
./src/pages/LandingPage/LandingPage.js
Module not found: Can't resolve '@material-ui/core/AppBar' in '....my path...../src/pages/LandingPage'

**Comment by TarikHuber** [comment]
Hi @terchris ,

Have you installed the npm packages? That looks like `@material-ui/core` is not installed.
Can you try to start with a fresh project using the script:

```npx create-react-app test-app --scripts-version rmw-react-scripts```

**Comment by terchris** [comment]
Hi @TarikHuber and thanks for the reply.
I found that the problem was that I was using node 11.2.0 This caused the fsevents to recompile with again created some errors related to python .. ouuch.

Installed node 10.13.0 and now it initiates, compiles and start just fine :)
