### ISSUE TITLE
yarn start: /usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by skypher** [TarikHuber/react-most-wanted#45]
Just installed via npx and tried to start, and I get this message:
```% yarn start
yarn run v1.13.0
$ react-scripts start
/usr/bin/env: ‘node\r’: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Looks like the project doesn't use UNIX line endings (plain \n) but either Mac (\r) or Windows (\r\n). I'm not sure how to fix this (and have no time to look into it further), but here's the report. :-)

**Comment by TarikHuber** [comment]
#37
