### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by zomars** [TarikHuber/react-most-wanted#5]
Hi!

I'm getting a compilation error due a new dependency:

```
Failed to compile.

./node_modules/material-ui-selectfield/es/SelectField.js
Module not found: Can't resolve 'react-infinite' in '/Users/zomars/Sites/ding-pwa/node_modules/material-ui-selectfield/es'
```

**Comment by TarikHuber** [comment]
Hi, 

We switched to the new library material-ui-selectfield from material-ui-superselectfield. That issue is already known and reported. I'll update to the newest version and hope that it is fixed. But installing the react-infinite in your project manually should fix this problem.

**Comment by zomars** [comment]
Thanks for the clarification!
