### ISSUE TITLE
refactor "componentWillMount" per changes to React standards

### ISSUE THREAD

**Issue by dimitrilw** [TarikHuber/react-most-wanted#52]
as of 01-Sep-2019 (most current commit is [20a012f|https://github.com/TarikHuber/react-most-wanted/commit/20a012fcf77426af367e11011aa8732843074a9c] ), the repo uses the componentWillMount lifecycle, which is flagged as "not recommended for use". The error message displayed in the console states:

> Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

> * Move code with side effects to componentDidMount, and set initial state in the constructor.
> * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

> Please update the following components: LoadableComponent

Note: while the example error message specifically identifies the LoadableComponent, there are other components generating the same warning.

## steps to replicate

* checkout current master branch; to use the exact same commit I was using at the time of the submission, checkout [20a012f|https://github.com/TarikHuber/react-most-wanted/commit/20a012fcf77426af367e11011aa8732843074a9c], e.g.: `git checkout 20a012f`
* run app, e.g.: `npm start`
* view errors in browser console, e.g.: `Ctrl-J` if using Google Chrome

**Comment by TarikHuber** [comment]
Hi @dimitrilw,

I'm catching the error message for a while but can't find any code in RMW or any of my libraries used in there that have the comonendWillMound inside. It's probably a deeper library. Unfortunately the error message doesn't give much or gives ro much info about it. I couldn't identify the library doing this but my eyes are on React Router or the Loading library because it happens on the most basic components. I will wait and see it goes away with updates of used libraries. In any case this should not be any problem using this project. I try to keep all dependencies up to date in matter of days 😀

**Comment by Maxblake** [comment]
Maybe there ?: [https://github.com/TarikHuber/react-most-wanted/blob/master/src/pages/About/About.js#L22](url)

**Comment by TarikHuber** [comment]
This is the whole code in that page

```
import React, { Component } from 'react'
import IconButton from '@material-ui/core/IconButton'
import { injectIntl } from 'react-intl'
import { GitHubIcon } from 'rmw-shell/lib/components/Icons'
import { Activity } from 'rmw-shell'
import ReactMarkdown from 'react-markdown'
import Scrollbar from 'rmw-shell/lib/components/Scrollbar/Scrollbar'
import README from './README.md'

require('github-markdown-css')

class About extends Component {
  // Sorry for using setState here but I have to remove 'marked' from the dependencies
  // because of a vulnerability issue
  constructor(props) {
    super(props)
    this.state = {
      text: ''
    }
  }

  componentWillMount() {
    fetch(README)
      .then(response => response.text())
      .then(text => {
        this.setState({ text: text })
      })
  }

  render() {
    const { intl } = this.props

    return (
      <Activity
        appBarContent={
          <IconButton href="https://github.com/TarikHuber/react-most-wanted" target="_blank" rel="noopener">
            <GitHubIcon />
          </IconButton>
        }
        title={intl.formatMessage({ id: 'about' })}
      >
        <Scrollbar>
          <div style={{ backgroundColor: 'white', padding: 12 }}>
            <ReactMarkdown className="markdown-body" source={this.state.text} />
          </div>
        </Scrollbar>
      </Activity>
    )
  }
}

export default injectIntl(About)

```

It can only be a library used there. But I see it also in all other pages.

**Comment by linusmartensson** [comment]
Just saw this while reading through issues.
When you implement the function "componentWillMount", as you do in the code above (second function), react will trigger the described warning. 
By replacing the function name with "componentDidMount" - the warning will disappear, and the code will execute as normally.

Maybe this is a fixed issue now though?

**Comment by TarikHuber** [comment]
How coould I not see the wrong name hahah thx for reminding me for this :smile:
