### ISSUE TITLE
Codelab needs login and access to gDrive?

### ISSUE THREAD

**Issue by leschekfm** [TarikHuber/react-most-wanted#55]
If anyone wants to view the [codelab ](https://codelabs-preview.appspot.com/?file_id=1cAjbZYRZkq4gXsllPOsPcDGXNyFmsWvr-oKjD_ZKeJ0#0)which is referenced in README.md, one is forced to login with his google account and also required to grant access to their google drive.

![image](https://user-images.githubusercontent.com/1288436/64600025-bd9be880-d3ba-11e9-9397-47cb40d7284a.png)

I don't want to grant access to all my files just to be able to read setup instructions. Also this is no requirement for other codelabs like https://codelabs.developers.google.com/codelabs/firestore-web/#0

What's the reason for this? At least to me this is very suspicious..

**Comment by TarikHuber** [comment]
Hi @leschekfm I total forgot about that codelab. I think the reason for this is that the others are hosted by google and this one is on my private Google Drive account. Can't remember if I published it on a website. While creating it I used the instructions from Google: https://github.com/googlecodelabs/tools

And it asks me also for the same rights -.-

If you want I can give you access to my G Drive source file so you can see it:
https://docs.google.com/document/d/1cAjbZYRZkq4gXsllPOsPcDGXNyFmsWvr-oKjD_ZKeJ0/edit?usp=sharing

**Comment by leschekfm** [comment]
Hi @TarikHuber 👋 
Yeah, reading through those instructions the problem is probably that it's still a non public preview, I guess.

I think it would be awesome if you could publish the codelab on github pages for this project like mentioned [here](https://github.com/googlecodelabs/tools#how-do-i-publish-my-codelabs)

**Comment by leschekfm** [comment]
You've got the quickest issue resolution time, I've seen for quite some time on github 😃 

Kudos to you @TarikHuber
