### ISSUE TITLE
After initialization there are uncommitted changes

### ISSUE THREAD

**Issue by leschekfm** [TarikHuber/react-most-wanted#56]
After running `npx create-react-app test-app --scripts-version rmw-react-scripts` as described in the README file my working directory contains uncommitted changes. 

```sh
$ git status
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    functions/gitignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        functions/.gitignore

no changes added to commit (use "git add" and/or "git commit -a")
```

I'm not sure if this additional gitignore file is even necessary and should be merged to the root one or if this should be fixed within https://github.com/TarikHuber/create-react-app

Unless it will be removed, I guess using the the synchronous move command `fs.moveSync` [here](https://github.com/TarikHuber/create-react-app/blob/master/packages/react-scripts/scripts/init.js#L170) should be sufficient to fix this.

**Comment by TarikHuber** [comment]
Do you have the same issu with default CRA?

The init file is the same as in default CRA. It could be an issue because I run the `npm i` command again in the functions folder and it needs more attention. Will check it ASAP.

**Comment by leschekfm** [comment]
Comparing the init file from CRA shows that this was added to your fork for the cloud functions subpackage, see https://github.com/facebook/create-react-app/compare/master...TarikHuber:master#diff-0ae46a2383dedcac5f5e369f5ca5f169R171

Looking at other monorepo projects like babel it seems that none keep individual .gitignore files within the subpackages but instead add the to be ignored files into the main .gitignore like you can see [here](https://github.com/babel/babel/blob/master/.gitignore#L6)

Therefore I'd vouch for removing [gitignore](https://github.com/TarikHuber/create-react-app/blob/master/packages/react-scripts/template/functions/gitignore) which would also allow to remove the added part from the init file.

**Comment by TarikHuber** [comment]
It should work now (https://github.com/TarikHuber/create-react-app/commit/7cc35b40a57f3a62d408fac37797365bf83bf6fc)

Can you try it out?

**Comment by leschekfm** [comment]
Works like a charm now 👍
