### ISSUE TITLE
Relation between this repo and the create-react-app fork

### ISSUE THREAD

**Issue by leschekfm** [TarikHuber/react-most-wanted#57]
Hi @TarikHuber 
As I was looking deeper into the project I was wondering about how the different repos are related. 

As far as I can see there is the [rmw-shell](https://github.com/TarikHuber/rmw-shell), the [react-most-wanted](https://github.com/TarikHuber/react-most-wanted) project and the [create-react-app fork](https://github.com/TarikHuber/create-react-app) which is used for creating new projects.

So as I understand it: 
1. the rmw-shell is the base project
2. the create-react-app fork takes that project and basically does what is listed in the [step-by-step install instructions](https://github.com/TarikHuber/rmw-shell/wiki/Step-by-step-installation)
3. this react-most-wanted project is the result of when you would use the CRA script

If that assumption is true I see a problem, as commits to the react-most-wanted project are not reflected within the CRA repo e.g. my typo fixes to the README are not included when running the CRA script nor are the package dependencies of the `functions` subproject up to date compared to this repo.

Did I get this right?

**Comment by TarikHuber** [comment]
Hi @leschekfm 

Yes that is absolutely how it works :)

Most of that is beacause all was created by time and some stuff before the other so I never come to find a solution to combine everything. I still don't have any idea how to do it :(

The CRA Fork needs to stay a fork. RMW need to stay a simple example and demo and rmw-shell a small library.

If you have any idea let me know :)

**Comment by leschekfm** [comment]
> Most of that is beacause all was created by time and some stuff before the other so I never come to find a solution to combine everything. I still don't have any idea how to do it :(

Yeah, that's what I thought 😃 

I guess then I'd propose to convert this project into a monorepo with the following packages:
1. `packages/shell` move the rmw-shell code in here
2. `packages/react-scripts` the forked files from CRA
3. `packages/demo` the output you get from the CRA scripts (could be updated automatically by CI)

As you only need the `react-scripts` part of CRA it should be possible to pull those files in using `git subtree` and also update them with changes from upstream, but I need to verify that. I think I've done something similar in another project before...

**Comment by leschekfm** [comment]
@TarikHuber I played around a bit with the monorepo approach and created a work in progress PR https://github.com/TarikHuber/react-most-wanted/pull/59

This should make it a lot easier to keep the CRA scripts and the demo part in sync. 

What do you think?

**Comment by TarikHuber** [comment]
Thx @leschekfm I wrote a comment on the PR

**Comment by TarikHuber** [comment]
Hi @leschekfm 

Create React App released a new way on how to create templates. You can now publish the template under a separate npm package. I have changed this project so it uses the new templating. Tahat way we don't need to fork the create-react-app project. Because of that the template can now be also the project we publish on the demo website. 

I hope you like it :)
