### ISSUE TITLE
Notification is not enabled for new accounts

### ISSUE THREAD

**Issue by ekbox** [TarikHuber/react-most-wanted#70]
When creating a new account at https://www.react-most-wanted.com/signin then heading to My Account page and switching notification on; notification is not enabled and remain disabled in Chrome on Mac and Samsung Note 5 and Safari. Service Worker is not added to browser even in incognito.

**Comment by TarikHuber** [comment]
The notifications are enabled by default if you accept the browser permission dialog. Did that dialog apear for your before you went to My Account? It also apears only if you go to the chat part of the app.

**Comment by ekbox** [comment]
Yes, went through the app and no dialog appeared for enablement. I checked site setting to see if it was on and there were none for the host.

**Comment by TarikHuber** [comment]
I have tested that on multiple decies with chrome and it works always. What browser are you using?
