### ISSUE TITLE
Instructions to remove the chat

### ISSUE THREAD

**Issue by samanyougarg** [TarikHuber/react-most-wanted#75]
Hi,

Thank you for creating this project. It is amazing.

Can you please provide instructions on how to remove the chat stuff as I want to use a blank boilerplate?

Thank you

**Comment by TarikHuber** [comment]
Hi and thx,

Just remove all menu items in the menuItems.js file in the configs and for restricting access by directly typing the URL write reoute revrites in your route configs so if someone enters `/chats` in you app he doesn't come to the chats at all.

**Comment by samanyougarg** [comment]
Cool, thank you.
