### ISSUE TITLE
Can't filter and use locales when using dynamic paths in CollectionActivity

### ISSUE THREAD

**Issue by linusmartensson** [TarikHuber/react-most-wanted#79]
If you define both a 'path' and a 'name', there seems to be a mismatch where filters and searches pass data to a filter identified by 'name', but it does not affect data collected in 'path' - so filters will not work if you use 'path'.
On the flipside, if you use 'name' and have a nested collection path, say '/user/{userId}/project', the CollectionActivity title uses 'name' to search for the internationalized document title, and I can't distinguish the two.

I would assume filters and searches should also index by "path || name" - much like watchCol sets up the state with firekit - and this would likely resolve the issue.

**Comment by TarikHuber** [comment]
Do you see the bug in the demo or in your own code?

**Comment by linusmartensson** [comment]
As far as I know, the demo doesn't have any part where names and paths differ. I worked around it for myself by cloning CollectionActivity and making the changes locally, but I still think it may need to be fixed.

**Comment by TarikHuber** [comment]
Can you send your fix as PR?
