### ISSUE TITLE
Should this work with latest Firebase-admin and Firebase-tools versions?

### ISSUE THREAD

**Issue by ElixirMike** [TarikHuber/react-most-wanted#81]
I had this working with the following versions in my function directory:

  "firebase-admin": "~7.0.0",
    "firebase-function-tools": "^1.1.3",
    "firebase-functions": "^2.2.0",

I then learned that in order to run functions locally on my machine using emulator, I needed to have Firebase-admin 8.0.0 or greater and firebase-functions 3.0.0 or greater.

I updated those versions and now when I run firebase deploy. I get "unexpected error".
My question is, is this version (1.1.3 ) compatible with the latest firebase-admin and firebase-functions versions?

It may be a different issue all together, but I'd like to know if this is the culprit or I need to look elsewhere.

**Comment by TarikHuber** [comment]
Hi. That project has no dependencies. Only peer dependencies so it uses the same firebase libraries as you do. Did you try to start the emulator without the code from `firebase-functions-tools`?

**Comment by ElixirMike** [comment]
yea, I found the issue was elsewhere. First I need to revert to a slighly earlier version of npm. That got me through the first hurdle. Then hit another error related to missing @firebase/app . I ran npm install firebase in my functions directory...and now all is well. 

By the way, love the solution on how it makes adding new Cloud Functions a breeze..well done.

**Comment by TarikHuber** [comment]
Thx 😄 I will close then this issue. Let me know if I can help elsewhere. I mean you helped yourself 😆
