### ISSUE TITLE
Feature Request - Apple Authentication

### ISSUE THREAD

**Issue by preconception** [TarikHuber/react-most-wanted#83]
Hey Tarik

_please delete or archive if you don't want to do this._

Can you try getting Sign in with Apple working with firebase and rmw?

**Comment by preconception** [comment]
https://www.youtube.com/watch?v=UafqYgRoIC0

nevermind! :)

**Comment by TarikHuber** [comment]
Hi @preconception ,

Unfortunately I never used Apple Login and don't see any usecase for me.
But the project is using the official [Firebase auth UI library](https://github.com/firebase/firebaseui-web). So if it's possible to do it using that you just need to change some configs in rmw to make it happen 😄
