### ISSUE TITLE
Move styles to a new folder

### ISSUE THREAD

**Issue by Prottoy2938** [TarikHuber/react-most-wanted#95]
I am suggesting we should move styles another file as opposed to inline style. What'd you think?

**Comment by TarikHuber** [comment]
Sorry. What styles do you mean?

**Comment by Prottoy2938** [comment]
inline styles

**Comment by TarikHuber** [comment]
Uh. I personaly like them to be there. If you like to separate them to a different file I'm open for PR-s. But I would not waste my time for that. I don't like to switch between files just to make some small changes. But as said jus my personal coding style. I know that separation of those is best practice. So if you want to do it I won't stop you ;)
